include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    avoid_print: true
    require_trailing_commas: true
    sort_child_properties_last: true
    unnecessary_this: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "lib/l10n/generated/**"
  errors:
    invalid_annotation_target: ignore # nécessaire avec hive_generator + Freezed-like patterns
